### ISSUE TITLE
Schema generation example

### ISSUE THREAD

**Issue by tutturen** [hallvard/graphql-emf#1]
Is there an example on how to use this to generate a GraphQL schema?

**Comment by hallvard** [comment]
Look in the tests project. Note that the schema is generated in memory, so it may be used for executing a query, not in a file.

**Comment by tutturen** [comment]
I see. Speaking of executing a query - does this generate an endpoint you can query?

**Comment by hallvard** [comment]
No, the end point (Servlet) generate the schema from the relevant EPackages, and then you respond to the request by executing a query. This will be demonstrated in the TDT4250 course.
